In [1]:
#Bài Tập 1
import numpy as np

In [101]:
#Câu 1: Khởi tạo mảng 1 chiều từ 4-10
arr = np.array(range(4,12))
print(arr)

[ 4  5  6  7  8  9 10 11]


In [47]:
#Câu 2: Tạo một mảng boolean 3x3 với tất cả giá true
arr1 = np.ones((3,3))
print(arr1 > 0) 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [87]:
#Câu 3: Lấy những phần tử mà thảo mãn một điều kiện cho trước của mảng 2 chiều
arr2 = np.random.randint(15, size = (3,3))
print(arr2)

[[ 2 14  1]
 [11  8  0]
 [ 5 12 12]]


In [88]:
#- Số lẻ
out1 = np.where(arr2 % 2 == 1)
print('Phần tử là số lẻ: \n', arr2[out1])

Phần tử là số lẻ: 
 [ 1 11  5]


In [89]:
#- Số chẵn
out2 = np.where(arr2 % 2 == 0)
print('Phần tử là số chẵn: \n', arr2[out2])

Phần tử là số chẵn: 
 [ 2 14  8  0 12 12]


In [77]:
#- Bội số của 3
out3 = np.where(arr2 % 3 == 0)
print('Phần tử là bội số của 3: \n', arr2[out3])

Phần tử là bội số của 3: 
 [6 3]


In [90]:
#Câu 4: Thay thế phần tử thoả mãn điều kiện cho trước bằng một giá trị khác
out4 = np.where(arr2 < 10, arr2, arr2 == 0)
print(out4)

[[2 0 1]
 [0 8 0]
 [5 0 0]]


In [102]:
#Câu 5: Chuyển định dạng (shape) của một ndarray. Chuyển mảng 1 chiều thành mảng 2 chiều
To2D = arr.reshape(4,2)
print(To2D)

[[ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [105]:
#Câu 6: Xếp chồng 2 mảng theo chiều dọc, chiều n
arrTest = np.vstack ((arr1, arr2)) 
print (arrTest)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 2. 14.  1.]
 [11.  8.  0.]
 [ 5. 12. 12.]]


In [114]:
#Câu 7: sử dụng repeat() và tile()
a = np.repeat(arr, 5)
print('Repeat: \n',a)

b = np.tile(arr, 3)
print('Tile: \n',b)

Repeat: 
 [ 4  4  4  4  4  5  5  5  5  5  6  6  6  6  6  7  7  7  7  7  8  8  8  8
  8  9  9  9  9  9 10 10 10 10 10 11 11 11 11 11]
Tile: 
 [ 4  5  6  7  8  9 10 11  4  5  6  7  8  9 10 11  4  5  6  7  8  9 10 11]


In [120]:
#Câu 8: Tìm phần tử chung của 2 mảng
A1 = np.array(range(1,7))
A2 = np.array(range(4,10))

test = np.array(set(A1)&set(A2))
print(test)

{4, 5, 6}
